/*
 * This source file was generated by the Gradle 'init' task
 */
package com.k.calc;

import org.junit.jupiter.api.Test;

import com.k.calc.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.t(), "app should have a greeting");
    }
}
